CREATE TABLE CHARGE 
(
    CHARGE_ID    NUMBER,
    SPORT_ID     NUMBER,
    CHARGE_YEAR  NUMBER,
    CHARGE_MONTH NUMBER,
    IF_INVALID   VARCHAR2(50),
    CONSTRAINT PK_CHARGE_ID PRIMARY KEY (CHARGE_ID),
    CONSTRAINT UK_CHARGE_VALID CHECK (IF_INVALID = 'VALID' OR IF_INVALID = 'INVALID')
);

ALTER TABLE CHARGE
ADD CONSTRAINT FK_CHARGE_SPORT FOREIGN KEY (SPORT_ID) REFERENCES SPORT (SPORT_ID);

ALTER TABLE CHARGE 
MODIFY SPORT_ID NOT NULL;
 
