CREATE TABLE COACH 
(
    COACH_ID     NUMBER,
    COACH_NAME   VARCHAR2(100),
    IF_INVALID   VARCHAR2(50),
    CONSTRAINT PK_COACH_ID PRIMARY KEY (COACH_ID),
    CONSTRAINT CH_VALID_COACH CHECK (IF_INVALID = 'VALID' OR IF_INVALID = 'INVALID')
);