CREATE TABLE COACH_DETAILS
(
    COACH_CODE      VARCHAR2(30),
    STARTING_HOUR   NUMBER,
    ENDING_HOUR     NUMBER,
    SPORT_ID        NUMBER, 
    
    CONSTRAINT UK_COACH_CODE UNIQUE (COACH_CODE)
);
ALTER TABLE COACH_DETAILS
ADD CONSTRAINT FK_COACH_SPORT FOREIGN KEY (SPORT_ID) REFERENCES SPORT(SPORT_ID);


