CREATE TABLE CUSTOMER_DETAILS
(
    CUSTOMER_CODE     VARCHAR2(30),
    BIRTH_DAY         DATE,
    GENDER            VARCHAR2(1),
    CREATEING_DATE    DATE,
    LOCATION_ID       NUMBER,
    CUSTOMER_PRO_CODE VARCHAR2(30),
    
    CONSTRAINT UK_CUSTOMER_CODE UNIQUE (CUSTOMER_CODE),
    CONSTRAINT FK_CUSTOMER_LOCATION FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID)
);

ALTER TABLE CUSTOMER_DETAILS
ADD  CONSTRAINT CH_CUSTOMER_GENDER CHECK (GENDER = 'F' OR GENDER = 'M');


