CREATE TABLE CUSTOMER 
(
    CUSTOMER_ID     NUMBER,
    CUSTOMER_NAME   VARCHAR2(100),
    CUSTOMER_PHONE  VARCHAR2(50),
    IF_INVALID      VARCHAR2(50),
    CONSTRAINT PK_CUSTOMER_ID PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT CH_VALID_CUSTOMER CHECK (IF_INVALID = 'VALID' OR IF_INVALID = 'INVALID')
);