CREATE TABLE CUSTOMER_SPORT_DETAILS
(
    CUSTOMER_SPORT_CODE  VARCHAR2(30),
    CUSTOMER_ID          NUMBER,
    STARTING_DATE_ONE    DATE,
    ENDING_DATE_ONE      DATE,
    STARTING_DATE_TWO    DATE DEFAULT NULL,
    ENDING_DATE_TWO      DATE DEFAULT NULL,
    SPORT_HOUR_ONE       NUMBER,
    SPORT_HOUR_TWO       NUMBER DEFAULT NULL,
    SPORT_ID_ONE         NUMBER,
    SPORT_ID_TWO         NUMBER DEFAULT NULL,
    COACH_ID_ONE         NUMBER,
    COACH_ID_TWO         NUMBER DEFAULT NULL,
    LAST_CHARGE_DATE_ONE DATE,
    LAST_CHARGE_DATE_TWO DATE,
    CONSTRAINT UK_CUSTOMER_SPORT_CODE UNIQUE (CUSTOMER_SPORT_CODE),
    CONSTRAINT CH_HOUR_NOT_SAME CHECK (SPORT_HOUR_ONE <> SPORT_HOUR_TWO),
    CONSTRAINT CH_SPORT_ID_NOT_SAME CHECK (SPORT_ID_ONE <> SPORT_ID_TWO),
    CONSTRAINT CH_COACH_NOT_SAME CHECK (COACH_ID_ONE <> COACH_ID_TWO)
);

ALTER TABLE CUSTOMER_SPORT_DETAILS
ADD CONSTRAINT FK_CUSTOMER_SPORT_TWO FOREIGN KEY (SPORT_ID_TWO) REFERENCES SPORT(SPORT_ID);

ALTER TABLE CUSTOMER_SPORT_DETAILS
ADD CONSTRAINT FK_CUSTOMER_SPORT_ONE FOREIGN KEY (SPORT_ID_ONE) REFERENCES SPORT(SPORT_ID);

ALTER TABLE CUSTOMER_SPORT_DETAILS
ADD CONSTRAINT FK_CUSTOMER_SPORT_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);

ALTER TABLE CUSTOMER_SPORT_DETAILS
ADD CONSTRAINT FK_CUSTOMER_SPORT_COACH_ONE FOREIGN KEY (COACH_ID_ONE) REFERENCES COACH(COACH_ID);

ALTER TABLE CUSTOMER_SPORT_DETAILS
ADD CONSTRAINT FK_CUSTOMER_SPORT_COACH_TWO FOREIGN KEY (COACH_ID_TWO) REFERENCES COACH(COACH_ID);








