CREATE OR REPLACE PACKAGE ERROR_PKG
IS 
    ONE_TWO_EQUAL          EXCEPTION;
    STARTING_BEFORE_ENDING EXCEPTION;
    TWO_IS_NULL            EXCEPTION;
    PRAGMA EXCEPTION_INIT(ONE_TWO_EQUAL, -20001);
    PRAGMA EXCEPTION_INIT(TWO_IS_NULL, -20002);
    PRAGMA EXCEPTION_INIT(STARTING_BEFORE_ENDING, -20003);
END;

