CREATE TABLE INVOICE_DETAILS 
(
   INVOICE_CODE         VARCHAR2(30),
   CUSTOMER_ID          NUMBER,
   LAST_CARGE_DATE_ONE  DATE,
   NEXT_CHARGE_DATE_ONE DATE, 
   LAST_CARGE_DATE_TWO  DATE DEFAULT NULL,
   NEXT_CHARGE_DATE_TWO DATE DEFAULT NULL,
   BANK_ACCOUNT         VARCHAR2(100),
   COST_SPORT_ONE       NUMBER,
   COST_SPORT_TWO       NUMBER DEFAULT NULL, 
   
   CONSTRAINT CH_INVOICE_CODE UNIQUE (INVOICE_CODE),
   CONSTRAINT FK_INVOICE_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

