CREATE TABLE INVOICE 
(
    INVOICE_ID     NUMBER,
    CUSTOMER_NAME  VARCHAR2(100),
    SPORT_NAME_ONE VARCHAR2(100),
    SPORT_NAME_TWO VARCHAR2(100) DEFAULT NULL,
    DAY_COUNT_ONE  NUMBER,
    DAY_COUNT_TWO  NUMBER  DEFAULT NULL,
    TOTAL_COST     NUMBER,
    INVOICE_DATE   DATE DEFAULT SYSDATE,
    REFUND_STATUS VARCHAR2(3),
    CONSTRAINT PK_INVOICE_ID PRIMARY KEY (INVOICE_ID),
    CONSTRAINT CH_SPORT_NAME_NOT_SAME CHECK (SPORT_NAME_ONE <> SPORT_NAME_TWO)
);

ALTER TABLE INVOICE
ADD CONSTRAINT CH_REFUND_STATUS CHECK (REFUND_STATUS = 'NO' OR REFUND_STATUS = 'YES');