CREATE TABLE LOG_DETAILS
(
    LOG_CODE       VARCHAR2(30),
    OPERATION_NAME VARCHAR2(50),
    OPERATION_DATE DATE,
    CUSTOMER_ID    NUMBER DEFAULT NULL,
    SPORT_ID       NUMBER DEFAULT NULL,
    COACH_ID       NUMBER DEFAULT NULL,
    PROMOTION_ID   NUMBER DEFAULT NULL,
    LOCATION_ID    NUMBER DEFAULT NULL,
    INVOICE_ID     NUMBER DEFAULT NULL,
    ERROR_CODE     NUMBER DEFAULT NULL,
    ERROR_DETAILS  VARCHAR2(100) DEFAULT NULL,
    BY_USER        VARCHAR2(50),
    
    CONSTRAINT UK_LOG_CODE UNIQUE (LOG_CODE),
    CONSTRAINT FK_LOG_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID),
    CONSTRAINT FK_LOG_SPORT FOREIGN KEY (SPORT_ID) REFERENCES SPORT (SPORT_ID),
    CONSTRAINT FK_LOG_COACH FOREIGN KEY (COACH_ID) REFERENCES COACH (COACH_ID),
    CONSTRAINT FK_LOG_PROMOTION FOREIGN KEY (PROMOTION_ID) REFERENCES PROMOTION (PROMOTION_ID),
    CONSTRAINT FK_LOG_LOCATION FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION (LOCATION_ID),
    CONSTRAINT FK_LOG_INVOICE FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE (INVOICE_ID)
);

