CREATE TABLE LOG
(
    LOG_ID         NUMBER,
    TABLE_NAME     VARCHAR2(100),
    IF_SUCCESSFUL  VARCHAR2(30),
    CONSTRAINT PK_LOG_ID PRIMARY KEY (LOG_ID),
    CONSTRAINT CH_SUCCESSFUL_LOG CHECK (IF_SUCCESSFUL = 'TRUE' OR IF_SUCCESSFUL = 'FALSE')
);