CREATE TABLE PROMOTION 
(
    PROMOTION_ID        NUMBER,
    CREATING_DATE       DATE,
    STARTING_DATE       DATE,
    ENDING_DATE         DATE,
    PROMOTION_TYPE      VARCHAR2(50),
    PROMOTION_CODE      VARCHAR2(30),
    PLAYER_COUNT        NUMBER,
    DISCOUNT_PERCENTAGE NUMBER,
    IF_INVALID          VARCHAR2(50),
    CONSTRAINT PK_PROMOTION_ID PRIMARY KEY (PROMOTION_ID),
    CONSTRAINT CH_VALID_PROMOTION CHECK (IF_INVALID = 'VALID' OR IF_INVALID = 'INVALID'),
    CONSTRAINT UK_RPOMOTION_CODE UNIQUE (PROMOTION_CODE),
    CONSTRAINT UK_RPOMOTION_TYPE UNIQUE (PROMOTION_TYPE)
);
