CREATE TABLE REFUND_INVOICE
(
    REFUND_ID               NUMBER,
    CUSTOMER_NAME           VARCHAR2(100),
    CANCEL_REGISTRATION_ONE DATE,
    CANCEL_REGISTRATION_TWO DATE DEFAULT NULL,
    REFUND_ONE              NUMBER,
    REFUND_TWO              NUMBER DEFAULT NULL,
    REFUND_TOTAL            NUMBER
);
ALTER TABLE REFUND_INVOICE
ADD CONSTRAINT PK_REFUND_ID PRIMARY KEY (REFUND_ID);


