CREATE OR REPLACE TRIGGER UPDATE_REFUND_STATUS
AFTER INSERT
ON REFUND_INVOICE
FOR EACH ROW
DECLARE 
BEGIN
    UPDATE INVOICE
    SET REFUND_STATUS = 'YES'
    WHERE INVOICE_ID = :NEW.INVOICE_ID;
END;